-- Phase 2 Milestone 0: Intelligence Layer schema (PHASE_2_IMPLEMENTATION.md).
-- Three new tables: actions (the action queue), api_budgets (DataForSEO
-- spend tracking), serp_snapshots (weekly SERP position data). Definitions
-- match ARCHITECTURE.md §3 exactly; CHECK constraints below are additions,
-- same "encode prose rules as DB constraints" discipline Milestone 1 used
-- for every enum/range documented only in prose there.

-- ============================================================================
-- ACTION QUEUE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.actions (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id          UUID NOT NULL REFERENCES public.sites(id) ON DELETE CASCADE,
  type             TEXT NOT NULL,
  priority_score   REAL NOT NULL,
  status           TEXT NOT NULL DEFAULT 'queued',
  title            TEXT NOT NULL,
  description      TEXT,
  source_module    TEXT NOT NULL,
  supporting_data  JSONB NOT NULL DEFAULT '{}',
  -- Nullable: not every action has an effort estimate at creation time.
  effort           TEXT,
  -- Nullable: free-text impact description, not every action generation
  -- rule in ARCHITECTURE.md §5 produces one.
  estimated_impact TEXT,
  -- ON DELETE SET NULL (not CASCADE): an action's history is meaningful
  -- even if the page/keyword it referenced is later deleted — matches
  -- ARCHITECTURE.md §3's own choice here, unlike every other page_id/
  -- keyword_id FK in this schema which CASCADEs.
  page_id          UUID REFERENCES public.pages(id) ON DELETE SET NULL,
  keyword_id       UUID REFERENCES public.keywords(id) ON DELETE SET NULL,
  completed_at     TIMESTAMPTZ,
  -- Nullable: auto-dismiss is optional per action; not every action
  -- generation rule sets an expiry (PHASE_2_IMPLEMENTATION.md Milestone 10
  -- resolves the default expiry window when the analysis engine ships).
  expires_at       TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT actions_type_check CHECK (type IN (
    'create_content', 'update_content', 'add_internal_link',
    'fix_cannibalization', 'fix_technical', 'update_meta', 'add_schema'
  )),
  CONSTRAINT actions_status_check CHECK (status IN (
    'queued', 'in_progress', 'completed', 'skipped', 'dismissed'
  )),
  CONSTRAINT actions_source_module_check CHECK (source_module IN (
    'keyword_intelligence', 'page_performance', 'cannibalization',
    'internal_linking', 'competitor', 'content_brief', 'decay'
  )),
  CONSTRAINT actions_effort_check CHECK (effort IS NULL OR effort IN ('small', 'medium', 'large')),
  CONSTRAINT actions_priority_score_check CHECK (priority_score >= 0),
  CONSTRAINT actions_supporting_data_is_object_check CHECK (jsonb_typeof(supporting_data) = 'object'),
  -- Mirrors sync_log's own status/completed_at consistency rule (ADR-009's
  -- general principle): a terminal status implies completed_at is set.
  CONSTRAINT actions_completed_at_consistency_check CHECK (
    (status IN ('completed', 'skipped', 'dismissed') AND completed_at IS NOT NULL) OR
    (status IN ('queued', 'in_progress') AND completed_at IS NULL)
  )
);

-- Supports: Action Queue UI's primary read pattern (ARCHITECTURE.md §7 —
-- "sorted by priority_score DESC" for a given site's open actions).
CREATE INDEX IF NOT EXISTS idx_actions_site_status ON public.actions(site_id, status, priority_score DESC);

COMMENT ON TABLE public.actions IS
  'The action queue — ranked, explainable recommendations generated by the Phase 2 scoring algorithms (ARCHITECTURE.md §5). Populated by the analysis engine (PHASE_2_IMPLEMENTATION.md Milestone 10).';

DROP TRIGGER IF EXISTS actions_set_updated_at ON public.actions;
CREATE TRIGGER actions_set_updated_at
  BEFORE UPDATE ON public.actions
  FOR EACH ROW EXECUTE FUNCTION public.seo_set_updated_at();

-- ============================================================================
-- DATAFORSEO BUDGET CONTROLS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.api_budgets (
  site_id         UUID NOT NULL REFERENCES public.sites(id) ON DELETE CASCADE,
  provider        TEXT NOT NULL,
  monthly_limit   REAL NOT NULL,
  current_spend   REAL NOT NULL DEFAULT 0,
  alert_threshold REAL NOT NULL DEFAULT 0.8,
  -- Always the 1st of its month — enforced below rather than trusted to
  -- application code, same pattern as keyword_page_metrics_weekly's
  -- week_start-is-Monday check.
  period_start    DATE NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (site_id, provider, period_start),
  CONSTRAINT api_budgets_provider_check CHECK (provider IN ('dataforseo', 'gsc', 'ga4')),
  CONSTRAINT api_budgets_monthly_limit_check CHECK (monthly_limit >= 0),
  CONSTRAINT api_budgets_current_spend_check CHECK (current_spend >= 0),
  CONSTRAINT api_budgets_alert_threshold_check CHECK (alert_threshold >= 0 AND alert_threshold <= 1),
  CONSTRAINT api_budgets_period_start_is_first_of_month_check CHECK (EXTRACT(DAY FROM period_start) = 1)
);

COMMENT ON TABLE public.api_budgets IS
  'Per-provider monthly spend tracking (ARCHITECTURE.md §6 Budget Controls). Checked before every DataForSEO call; the call is skipped and logged as budget_exceeded once current_spend >= monthly_limit.';

DROP TRIGGER IF EXISTS api_budgets_set_updated_at ON public.api_budgets;
CREATE TRIGGER api_budgets_set_updated_at
  BEFORE UPDATE ON public.api_budgets
  FOR EACH ROW EXECUTE FUNCTION public.seo_set_updated_at();

-- ============================================================================
-- SERP SNAPSHOTS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.serp_snapshots (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  site_id       UUID NOT NULL REFERENCES public.sites(id) ON DELETE CASCADE,
  keyword_id    UUID NOT NULL REFERENCES public.keywords(id) ON DELETE CASCADE,
  date          DATE NOT NULL,
  position      SMALLINT NOT NULL,
  url           TEXT NOT NULL,
  domain        TEXT NOT NULL,
  is_own_site   BOOLEAN NOT NULL DEFAULT false,
  serp_feature  TEXT NOT NULL DEFAULT 'organic',
  -- Nullable: not every SERP result has a title (e.g. some rich-result
  -- types omit it).
  title         TEXT,
  -- Rows are immutable once inserted — a snapshot for a given
  -- keyword/date/position never changes, only new snapshots are added —
  -- so, per Milestone 1's own rule ("every table with a column that can
  -- change post-insert also gets updated_at"), this needs created_at only.
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT serp_snapshots_keyword_date_position_key UNIQUE (keyword_id, date, position),
  -- No fixed upper bound: unlike GSC's own documented 1-1000 range
  -- (keyword_page_metrics.position), DataForSEO's SERP endpoint has no
  -- similarly authoritative documented ceiling to encode here.
  CONSTRAINT serp_snapshots_position_check CHECK (position >= 1),
  CONSTRAINT serp_snapshots_serp_feature_check CHECK (serp_feature IN (
    'organic', 'featured_snippet', 'paa', 'local_pack', 'video', 'image'
  ))
);

-- Supports: per-site, per-keyword trend queries over time (Cannibalization
-- and competitor-tracking read patterns, ARCHITECTURE.md §5.3/Phase 3).
CREATE INDEX IF NOT EXISTS idx_serp_site_kw_date ON public.serp_snapshots(site_id, keyword_id, date);
-- Supports: competitor-domain lookups (Phase 3), added now since the
-- column exists and the query pattern is already documented in
-- ARCHITECTURE.md §3, cheap to add alongside the table rather than as a
-- later ALTER.
CREATE INDEX IF NOT EXISTS idx_serp_domain ON public.serp_snapshots(domain);

COMMENT ON TABLE public.serp_snapshots IS
  'Weekly SERP position snapshots for tracked keywords (ARCHITECTURE.md §6, DataForSEO SERP > Regular). Populated by PHASE_2_IMPLEMENTATION.md Milestone 6.';

-- ============================================================================
-- RLS — same default-deny posture as every existing SEO table (Milestone 1):
-- enabled, zero anon/authenticated policies. service_role (BYPASSRLS) is
-- the only role with access, via src/lib/supabase/server.ts.
-- ============================================================================

ALTER TABLE public.actions        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_budgets    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.serp_snapshots ENABLE ROW LEVEL SECURITY;
